version: 2
updates:
  # 1. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # 2. .NET NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    # GROUPS THEM ALL TOGETHER IN PR:
    groups:
      everything:
        patterns:
          - "*" 
